version: '3.8'

services:
  # Development service
  dev:
    build:
      context: .
      target: build
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: npm run dev -- --host 0.0.0.0
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:3000
    networks:
      app-network:
        aliases:
          - permah-dev
    hostname: permah-dev

  # Production service
  prod:
    build: .
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=https://api.yourdomain.com
    networks:
      app-network:
        aliases:
          - permah-prod
    hostname: permah-prod

  # Reverse proxy
  proxy:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx.proxy.conf:/etc/nginx/conf.d/default.conf
    networks:
      app-network:
        aliases:
          - permah.local
    depends_on:
      - dev
      - prod

networks:
  app-network:
    driver: bridge
    name: permah-network 